### ISSUE TITLE
error after npm install

### ISSUE THREAD

**Issue by raseraser** [reduction-admin/react-reduction#96]
tried npm 18.16.1 & 14.21.3 , same error
'gyp verb `which` failed Error: not found: python2'

E:\h5\react-reduction>yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning "react-infinite-calendar > recompose@0.22.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
[4/4] Building fresh packages...
error B:\h5\react-reduction\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: B:\h5\react-reduction\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe B:\h5\react-reduction\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'B:\\h5\\react-reduction\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.21.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at B:\h5\react-reduction\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at B:\h5\react-reduction\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (B:\h5\react-reduction\node_modules\node-gyp\node_modules\which\which.js:68:19)

**Comment by vallamost** [comment]
this project is abandoned :(
